Repository petrobras/ross, pull requests merged in 2019-06, with the labels that each got.

#152 Fix Campbell's strange behavior for precession
  ross/rotor_assembly.py
Labels: bug

#155 Fix equality for bearing element
  ross/bearing_seal_element.py
  ross/tests/test_bearing_seal_element.py
Labels: bug

#151 Add import to Axes3d
  ross/results.py
  ross/rotor_assembly.py
Labels: bug

#178 Improvements for plotting results
  ross/results.py
  ross/rotor_assembly.py
Labels: bug, enhancement

#182 Implementing tests for H_kappa
  ross/tests/test_rotor_assembly.py
Labels: testing

#184 interactions with rotor plotting
  ross/disk_element.py
  ross/shaft_element.py
Labels: enhancement
