Repository petrobras/ross, pull requests merged in 2019-08, with the labels that each got.

#234 Improving plot rotor
  ross/bearing_seal_element.py
  ross/disk_element.py
Labels: enhancement

#232 Add Check slenderness ratio method
  ross/rotor_assembly.py
  ross/shaft_element.py
Labels: enhancement

#244 Make Free-Body Diagram more readable
  ross/results.py
Labels: bug, enhancement

#252 Some changes in Tutorial and Installation
  docs/examples/tutorial.ipynb
  docs/installation.rst
Labels: documentation

#233 Fix inconsistencies in the mass and gyroscopic matrices; New tests for shaft tapered element
  ross/shaft_element.py
  ross/tests/test_shaft_element.py
Labels: bug, testing

#249 Replace bearing plot style / remove element length dependency from glyphs
  ross/bearing_seal_element.py
  ross/disk_element.py
  ross/rotor_assembly.py
Labels: enhancement

#256 Fix typo in __repr__
  ross/bearing_seal_element.py
Labels: bug
