Repository petrobras/ross, pull requests merged in 2020-07, with the labels that each got.

#615 Test for the 'MagneticBearingElement' class
  ross/tests/test_bearing_seal_element.py
Labels: testing

#608 Add file to configurate rotordynamic report
  ross/config.py
Labels: enhancement

#623 Set default values to log_dec color scale
  ross/results.py
Labels: enhancement

#625 Replace interp1d by line_shape from Plotly
  ross/results.py
Labels: enhancement

#629 General improvements in plot_random_var()
  ross/stochastic/st_bearing_seal_element.py
  ross/stochastic/st_disk_element.py
  ross/stochastic/st_materials.py
  ross/stochastic/st_point_mass.py
  ross/stochastic/st_results_elements.py
  ross/stochastic/st_shaft_element.py
  ross/tests/test_stochastic_elements.py
Labels: enhancement

#631 Formatting __str__methods to include units
  ross/disk_element.py
  ross/materials.py
  ross/point_mass.py
  ross/shaft_element.py
Labels: documentation

#635 Add probe argument to ForcedResponseResults
  ross/api_report.py
  ross/results.py
  ross/rotor_assembly.py
Labels: api change, enhancement
