Repository petrobras/ross, pull requests merged in 2020-02, with the labels that each got.

#407 Fix links not working for more than one support
  ross/bearing_seal_element.py
  ross/disk_element.py
  ross/element.py
  ross/point_mass.py
  ross/rotor_assembly.py
  ross/shaft_element.py
  ross/tests/test_bearing_seal_element.py
  ross/tests/test_disk_element.py
  ross/tests/test_point_mass.py
  ross/tests/test_rotor_assembly.py
  ross/tests/test_shaft_element.py
Labels: bug

#444 Fix bearing position bug
  ross/rotor_assembly.py
Labels: bug

#432 Updating PR 360 and other small changes
  ross/api_report.py
  ross/bearing_seal_element.py
  ross/disk_element.py
  ross/element.py
  ross/materials.py
  ross/rotor_assembly.py
  ross/rotors/Benchmarks/elements/BearingElement.toml
  ross/rotors/Benchmarks/elements/DiskElement.toml
  ross/rotors/Benchmarks/elements/ShaftElement.toml
  ross/rotors/Benchmarks/properties.toml
  ross/rotors/Rotor_format/elements/bearing_seal_elements.toml
  ross/rotors/Rotor_format/elements/disk_elements.toml
  ross/rotors/Rotor_format/elements/shaft_elements.toml
  ross/rotors/Rotor_format/properties.toml
  ross/shaft_element.py
  ross/tests/test_rotor_assembly.py
  ross/utils.py
Labels: api change, enhancement

#449 Add mode_shape 2D graph
  ross/results.py
  ross/rotor_assembly.py
Labels: enhancement

#433 Updating PR 287
  ross/api_report.py
  ross/bearing_seal_element.py
  ross/materials.py
  ross/rotor_assembly.py
Labels: api change, enhancement

#450 Add CoAxialRotor class
  ross/bearing_seal_element.py
  ross/disk_element.py
  ross/rotor_assembly.py
  ross/tests/test_rotor_assembly.py
Labels: enhancement
