Repository petrobras/ross, pull requests merged in 2020-06, with the labels that each got.

#581 More efficient code for static analysis
  ross/results.py
  ross/rotor_assembly.py
  ross/tests/test_rotor_assembly.py
Labels: bug, enhancement

#574 Add methods to plot the deflected shape
  ross/results.py
  ross/rotor_assembly.py
Labels: enhancement

#587 Pinned pytest version to 4.6 or superior
  setup.py
Labels: bug

#584 Warning to extrapolating coefficients
  ross/rotor_assembly.py
Labels: enhancement

#588 Move "sparse" argument to run_modal()
  ross/api_report.py
  ross/rotor_assembly.py
  ross/stochastic/st_rotor_assembly.py
Labels: api change, enhancement

#594 Fix ValueError when inputting an integer to disk properties
  ross/disk_element.py
Labels: bug

#596 Fix index to slice modal parameters
  ross/rotor_assembly.py
Labels: bug

#598 Include option for clustering points to other methods
  ross/rotor_assembly.py
Labels: enhancement

#582 Add plotly theme
  ross/__init__.py
  ross/fluid_flow/fluid_flow_graphics.py
  ross/plotly_theme.py
  ross/results.py
  ross/rotor_assembly.py
  ross/tests/test_rotor_assembly.py
Labels: enhancement
