Repository petrobras/ross, pull requests merged in 2020-12, with the labels that each got.

#717 Calculate velocity and acceleration responses
  ross/results.py
  ross/rotor_assembly.py
  ross/stochastic/st_rotor_assembly.py
  ross/tests/test_results.py
  ross/tests/test_rotor_assembly.py
Labels: api change, enhancement

#719 Customizing mode shape titles
  ross/results.py
  ross/rotor_assembly.py
Labels: enhancement

#722 Fix DoF error when using "n_link"
  ross/defects/abs_defect.py
  ross/results.py
  ross/rotor_assembly.py
  ross/tests/test_results.py
Labels: bug

#725 Improve contributing docs
  CONTRIBUTING.rst
Labels: documentation

#729 Add units to stochastic ross module
  ross/stochastic/st_bearing_seal_element.py
  ross/stochastic/st_disk_element.py
  ross/stochastic/st_materials.py
  ross/stochastic/st_point_mass.py
  ross/stochastic/st_results.py
  ross/stochastic/st_rotor_assembly.py
  ross/stochastic/st_shaft_element.py
  ross/tests/test_stochastic_rotor_assembly.py
Labels: enhancement

#732 Add function to collect and organize data from figures
  ross/__init__.py
  ross/utils.py
Labels: enhancement
