Repository petrobras/ross, pull requests merged in 2020-08, with the labels that each got.

#638 Change .use_material() to .load_material()
  ross/materials.py
  ross/shaft_element.py
  ross/tests/test_materials.py
Labels: api change, enhancement

#639 Add probe argument to TimeResponseResults
  ross/results.py
  ross/rotor_assembly.py
Labels: enhancement

#641 Remove repetitive command line
  ross/fluid_flow/fluid_flow.py
Labels: bug, enhancement

#643 Changing TimeResponseResults API
  ross/results.py
  ross/rotor_assembly.py
Labels: api change

#645 fix dof of unbalanced force
  ross/rotor_assembly.py
Labels: bug
