Repository petrobras/ross, pull requests merged in 2021-01, with the labels that each got.

#737 Add optional to change material's colors from excel file
  ross/shaft_element.py
  ross/tests/data/shaft_si.xls
  ross/tests/data/shaft_us.xls
  ross/utils.py
Labels: enhancement

#741 Documentation Fluid-Flow
  docs/examples.rst
  docs/examples/example_9.ipynb
  docs/examples/fluid_flow_elliptical_bearing.ipynb
  docs/examples/fluid_flow_short_bearing.ipynb
  docs/examples/fluid_flow_theory.ipynb
  docs/examples/fluid_flow_wear_bearing.ipynb
  ross/fluid_flow/fluid_flow_graphics.py
Labels: documentation

#742 Revert "Add codecov to appveyor"
  appveyor.yml
Labels: bug

#743 Add Black, Isort and Codecov to workflow
  .github/workflows/deploy-docs.yml
  .github/workflows/test.yml
  ross/__init__.py
  ross/rotor_assembly.py
  setup.py
Labels: enhancement
